### ISSUE TITLE
Adafruit_LSM9DS1 doesn't pass it's Wire Instance to Magnetometer

### ISSUE THREAD

**Issue by pavitter-bluestone** [adafruit/Adafruit_LSM9DS1#12]
- Arduino board:  Arduino Nano 33 BLE Sense
- IDE: Plattform IO

While trying to use the internal LSM9DS1 of the Arduino Nano 33 BLE Sense, i noticed that it didn't found the sensor.
The Arduino Nano 33 BLE Sense has it's internal LSM9DS1 attached to the Wire1 instance.
After passing the correct Wire instance to the Adafruit_LSM9DS1 Constructor, the library still didn't found the LSM.

After looking in the source code, i noticed that in Adafruit_LSM9DS1.cpp, Line 133, that the wire instance is not passed to the magnetometer beginn function.

I changed the line 133 in Adafruit_LSM9DS1.cpp, from
`if (!_magSensor.begin_I2C(LSM9DS1_ADDRESS_MAG)) {`
to 
`if (!_magSensor.begin_I2C(LSM9DS1_ADDRESS_MAG, _wire)) {`

After this change, the library found the internal LSM of the Arduino Nano 33 BLE Sense.

To reproduce the bug it should suffice to attach a LSM9DS1 to an I2C Connection, that doesn't map to the normal Wire instance.

I hope it helps.

**Comment by ladyada** [comment]
nice, can you submit a PR? thanks :)
