### ISSUE TITLE
Unable to initialize the LSM9DS1 with nrf52 

### ISSUE THREAD

**Issue by prisikarm** [adafruit/Adafruit_LSM9DS1#17]
In this particular case, I am using nano 33 BLE, so wiring is not a problem for sure.
It is stuck with the message `Oops ... unable to initialize the LSM9DS1. Check your wiring!`

**Comment by caternuson** [comment]
Please post this in the forums along with photos of your setup:
https://forums.adafruit.com/

Not sure how using a Nano 33 BLE makes wiring a non-issue?

**Comment by prisikarm** [comment]
Wiring is not an issue, since LSM9DS1is soldered directly on the board, and everything is working with other libraries.

**Comment by caternuson** [comment]
Must be an Arduino Nano 33 BLE ***Sense***. Does the LSM show up in an I2C address scan?
https://playground.arduino.cc/Main/I2cScanner/

**Comment by ladyada** [comment]
@prisikarm theres' all sorts of stuff going on with the BLE sense to enable I2C - you'll want to contact arduino forums for support on how to do that!
