### ISSUE TITLE
Gyroscale bits are set at wrong bit location

### ISSUE THREAD

**Issue by JanSurft** [adafruit/Adafruit_LSM9DS1#19]
According to the datasheet of the lsm9ds1 (https://www.st.com/resource/en/datasheet/lsm9ds1.pdf), the bits to set the gyro scale are at these bitpositions: `0b00011000` but the sensor library does a left shift of `4` which leads to the wrong setting for gyro scale.

Also it unsets the wrong bits: 
`reg &= ~(0b00110000);`

**Comment by caternuson** [comment]
hmm. yep, looks like:
![image](https://user-images.githubusercontent.com/8755041/133893292-62643d25-cab9-4bc5-be69-489dbbebffdb.png)

good use for registerbits

**Comment by caternuson** [comment]
@JanSurft Thanks for pointing this out. Were you planning to PR a fix also?
