### ISSUE TITLE
Bitmask error in Adafruit_LSM9DS1::setupGyro()

### ISSUE THREAD

**Issue by jdimpson** [adafruit/Adafruit_LSM9DS1#2]
I'm trying to create a Python implementation for LSM9DS1, so i don't have patches to submit (and in the interests of fairness and transparency, I don't have any validated code yet myself, which is why I'm reviewing yours).

But I noticed an error in setupGyro(). Specifically, line 304 of Adafruit_LSM9DS1.cpp [https://github.com/adafruit/Adafruit_LSM9DS1/blob/master/Adafruit_LSM9DS1.cpp#L304](url), bitwise-ANDs the current value of CTRL_REG1_G, with the bit pattern 00110000, in preparation for bitwse-OR with a new shifted 2-bit scale value. I believe this pattern is wrong. It should be 00011000.

According to the DocID025715 Rev 3 (March 2015) of STMicroelectronics' datasheet at [http://www.st.com/content/ccc/resource/technical/document/datasheet/1e/3f/2a/d6/25/eb/48/46/DM00103319.pdf/files/DM00103319.pdf/jcr:content/translations/en.DM00103319.pdf](url), the CTRL_REG1_G register is defined such that the first three bits control the Output Data Rate, the next two bits control the Full Scale selection, the next bit is always 0, and the last two bits control the Bandwidth selection. (See Section 7.12 pg 45 of 72)  This copy of table 44 illustrates the register:

> ODR_G2 | ODR_G1 | ODR_G0 | FS_G1 | FS_G0 | 0 | BW_G1 | BW_G0

The new scale value needs to be inserted into bit positions FS_G1 and FS_G0, so the 1's in the bitmask need to be adjusted.

Accordingly, in Adafruit_LSM9DS1.h line 171, the scaling values in enumeration lsm9ds1GyroScale_t [https://github.com/adafruit/Adafruit_LSM9DS1/blob/master/Adafruit_LSM9DS1.h#L171](url) should be left-shifted 3 positions, not 4, to line up as well, so the bitwise-OR successfully sets the new scale into the FS_G1 and FS_G0 positions. 

Thank you!

**Comment by deanm1278** [comment]
fixed!
https://github.com/adafruit/Adafruit_LSM9DS1/commit/b08fb3c2c04b64bd5d29462c3c99eabdb0ace79a
