### ISSUE TITLE
Specify and include license

### ISSUE THREAD

**Issue by TheLastProject** [adafruit/Adafruit_LSM9DS1#4]
https://github.com/adafruit/Adafruit_LSM9DS1/blob/master/Adafruit_LSM9DS1.cpp#L13 states the following: "BSD license, all text above must be included in any redistribution".

However, this license is not included in any of your files, nor is the license header there. On top of that, there are 3 different BSD licenses according to the OSI: https://opensource.org/licenses/alphabetical.

I assume you meant to use the 3-Clause BSD license on https://opensource.org/licenses/BSD-3-Clause. Could you specify this as per https://wiki.opensource.org/bin/Main/Projects/OSI+Website+Page+Improvements/How+to+apply+an+open+source+license+to+your+project/?

**Comment by ladyada** [comment]
hiya it is https://opensource.org/licenses/BSD-3-Clause
thanks!
