### ISSUE TITLE
Wrong mask for Gyro scale

### ISSUE THREAD

**Issue by leinardi** [adafruit/Adafruit_LSM9DS1#6]
https://github.com/adafruit/Adafruit_LSM9DS1/blob/c5759802e5de390d774db004a6f0972fbfbd99d6/Adafruit_LSM9DS1.cpp#L304

The right map should be `0b00011000` as stated in the datasheet Table 44 page 45.

**Comment by deanm1278** [comment]
fixed!
https://github.com/adafruit/Adafruit_LSM9DS1/commit/b08fb3c2c04b64bd5d29462c3c99eabdb0ace79a
